module.exports = {
	locales: {
		'/en/': {
			lang: 'en-US',
			path: '/en/',
			label: 'English',
			englishLabel: 'English',
			title: 'Stdkooludarkus',
			description: 'Stdkooludarkus de bisonee',
		},
		'/zh/': {
			lang: 'zh-CN',
			path: '/zh/',
			label: '中文',
			englishLabel: 'Chinese',
			title: '臓真足民手',
			description: '子本撃康企境暮検靖合探間為欺罪京案記玲。',
		},
		'/ru/': {
			lang: 'ru-RU',
			path: '/ru/',
			label: 'Русский',
			englishLabel: 'Russian',
			title: 'Пертинациа',
			description: 'Феугиат демоцритум сцрибентур ет мел.',
		},
		'/de/': {
			lang: 'de-DE',
			path: '/de/',
			label: 'Deutsch',
			englishLabel: 'German',
			title: 'Dramatügo',
			description: 'Dtrüdmato grötzigültiga matru damates hurganes.',
		},
		'/ja/': {
			lang: 'ja-JP',
			path: '/ja/',
			label: '日本人',
			englishLabel: 'Japanies',
			title: '',
			description: '',
		},
		'/sv/': {
			lang: 'sv-SE',
			path: '/sv/',
			label: 'Svenska',
			englishLabel: 'Swedish',
			title: '',
			description: '',
		},
		'/th/': {
			lang: 'th-TH',
			path: '/th/',
			label: 'ไทย',
			englishLabel: 'Thai',
			title: '',
			description: '',
		},
		'/cs/': {
			lang: 'cs-CZ',
			path: '/cs/',
			label: 'Čeština',
			englishLabel: 'Czech',
			title: '',
			description: '',
		},
		'/it/': {
			lang: 'it-IT',
			path: '/it/',
			label: 'Italiano',
			englishLabel: 'Italian',
			title: '',
			description: '',
		},
		'/es/': {
			lang: 'es-ES',
			path: '/es/',
			label: 'Español',
			englishLabel: 'Spanish',
			title: '',
			description: '',
		},
		'/el/': {
			lang: 'el-GR',
			path: '/el/',
			label: 'Ελληνικά',
			englishLabel: 'Greek',
			title: '',
			description: '',
		},
		'/hi/': {
			lang: 'hi-IN',
			path: '/hi/',
			label: 'हिंदी',
			englishLabel: 'Hindi',
			title: '',
			description: '',
		},
		'/ko/': {
			lang: 'ko-KR',
			path: '/ko/',
			label: '한국어',
			englishLabel: 'Korean',
			title: '',
			description: '',
		},
		'/hr/': {
			lang: 'hr-HR',
			path: '/hr/',
			label: 'Hrvatski',
			englishLabel: 'Croatian',
			title: '',
			description: '',
		},
		'/pl/': {
			lang: 'pl-PL',
			path: '/pl/',
			label: 'Polskie',
			englishLabel: 'Polish',
			title: '',
			description: '',
		},
		'/uk/': {
			lang: 'uk-UA',
			path: '/uk/',
			label: 'Українська',
			englishLabel: 'Ukrainian',
			title: '',
			description: '',
		},
		'/tr/': {
			lang: 'tr-TR',
			path: '/tr/',
			label: 'Türk',
			englishLabel: 'Turkish',
			title: '',
			description: '',
		},
		'/fr/': {
			lang: 'fr-FR',
			path: '/fr/',
			label: 'Français',
			englishLabel: 'French',
			title: '',
			description: '',
		},
		'/ar/': {
			lang: 'ar-SA',
			path: '/ar/',
			label: 'عربى',
			englishLabel: 'Arabic',
			title: '',
			description: '',
		},
	},
	themeConfig: {
		'/en/': {
			selectText: 'Language',
			label: 'English',
		},
		'/zh/': {
			selectText: '语言',
			label: '中文',
		},
		'/ru/': {
			selectText: 'Язык',
			label: 'Русский',
		},
	},
}
